name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CREATE_SUPERUSER: false
      DJANGO_SUPERUSER_EMAIL: admin@example.com  # Change this to your superuser email

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        set -o errexit
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect Static Files
      run: |
        set -o errexit
        python manage.py collectstatic --noinput

    - name: Run Migrations
      run: |
        set -o errexit
        python manage.py migrate

    - name: Create Superuser (if enabled)
      if: env.CREATE_SUPERUSER == 'true'
      run: |
        set -o errexit
        python manage.py createsuperuser --noinput --email "$DJANGO_SUPERUSER_EMAIL"

    - name: Start Django Server
      run: |
        set -o errexit
        python manage.py runserver 0.0.0.0:8000
